### ISSUE TITLE
Remove Jekyll-related metadata

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg-data-starter#7]
There is metadata left-over that is specific to Jekyll. We should be fine to remove these. I believe they are "permalink" and "layout".

**Comment by brockfanning** [comment]
Permalink and layout have been removed, but I we could also remove "published", which is still there.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning the published field isn't in the indicator config files so this should be resolved with #43
